"""add trader error table

Revision ID: 57b0b0d6b81a
Revises: 606b354140e8
Create Date: 2023-08-01 22:48:07.049261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b0b0d6b81a'
down_revision = '606b354140e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traderrequesterrors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traderrequesterrors'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traderrequesterrors')
    # ### end Alembic commands ###
