version: '3.9'

services:
  db:
    image: 'postgres:12.5-alpine'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: ${APPLICATION_NAME}_db
    env_file:
      - .env
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    image: ${IMAGE_NAME}
    container_name: ${APPLICATION_NAME}
    env_file:
      - .env
    depends_on:
      - db