version: '3.9'

services:
  db:
    image: 'postgres:12.5-alpine'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: ${APPLICATION_NAME}_db
    env_file:
      - .env
    ports:
      - '5432:5432'
